### ISSUE TITLE
Allow user to decide which device this package works with

### ISSUE THREAD

**Issue by ruben00001** [Etto91/react-scroll-wheel-handler#16]
This seems to be working well overall. Thanks!

However, it'd be good if I could decide whether I want the `upHandler` to only apply to scrolling and not to the up arrow key nor an 'up' swipe, for instance. 

It's kind of breaking for me.

I guess this is a feature request.

**Comment by Etto91** [comment]
hi, thank you for use it. could you make a pr? i think that is easy to implement.

**Comment by ruben00001** [comment]
> hi, thank you for use it. could you make a pr? i think that is easy to implement.

I've never contributed to a package before but I'll give it a go.

**Comment by Etto91** [comment]
@ruben00001 i've added disableSwipe prop in 2.0.1...tell me if that's what you wanted

**Comment by ruben00001** [comment]
@Etto91 Almost. It'd be good to be able to do the same for all devices: keyboard, mouse and touch device swiping. I'm happy to give this a go next week I've just been busy.
