### ISSUE TITLE
handler callbacks not returning the event value and focus issue

### ISSUE THREAD

**Issue by vmc08** [Etto91/react-scroll-wheel-handler#17]
Hi @Etto91 , great work on this helpful utility component.

I noticed that when using keyboard arrow keys, the event isn't returned and is only available when scrolling (refer to image)

**first log was from scrolling
2nd one was from arrow keys**
![image](https://user-images.githubusercontent.com/12130528/95184371-d6631180-07f9-11eb-9e77-ffe111cd20ce.png)

Also another thing to point out is that whenever I'm already focusing on components outside your utility (somewhere on the yellowed section) and pressing the arrow keys, the event still being fired when the expected behavior is shouldn't because I'm no longer focusing on the scrolling section (which is on the left section).

![image](https://user-images.githubusercontent.com/12130528/95184756-6acd7400-07fa-11eb-99b9-e4c00cf40b25.png)

I checked the code and found the potential lines why it's happening, cloned it locally and it seems it's working as expected after doing the necessary changes. I tried submitting a PR but seems like I can't push my code into your repo under different branch name, haven't tried submitting PR before anyways.

**Comment by Etto91** [comment]
hi @vmc08, 
i will check meanwhile check this https://jarv.is/notes/how-to-pull-request-fork-github/ and try to make a pr :)

**Comment by vmc08** [comment]
@Etto91 thanks for your fast response, already submitted a PR. Thanks for the resource too!
