### ISSUE TITLE
Wheel event doesn't work on Windows

### ISSUE THREAD

**Issue by JimmyBeldone** [Etto91/react-scroll-wheel-handler#2]
Hi,

Thank you for this package, it works great en MacOS, but I recently noticed that it does not work on Windows. The wheel event does not fire up or down handler. 

Any idea why ?

Thanks again

**Comment by Etto91** [comment]
does not work on all browsers?

**Comment by JimmyBeldone** [comment]
Only tried on chrome and firefox

**Comment by Etto91** [comment]
ty...I will check as soon as possible

**Comment by JimmyBeldone** [comment]
Thanks. I'm looking into it as well.

**Comment by JimmyBeldone** [comment]
Tested on two different Windows devices :

`e.wheelDelta` is either 100 or -100, 
so `this.trainData` is always `[100, 100, 100, 100]`, 
which always return *false*  in your condition `this.checkIfIncrease(this.trainData)`

You use `checkIfIncrease()` to detect inertia scroll right?
This might help : https://github.com/d4nyll/lethargy

**Comment by Etto91** [comment]
> You use `checkIfIncrease()` to detect inertia scroll right?
yes.

> This might help : https://github.com/d4nyll/lethargy
oh yes..It seems like it's what I've been looking for a long time..if you want you can make a pr replacing checkIfIncrease function with lethargy ...otherwise i will try to do it tonight

**Comment by Etto91** [comment]
i have integrate lethargy here #3 
if you can test it, you'd do me a favor because otherwise i need to find a windows device.
i have tested it with parallels on mac on w10..with parallels works.
@JimmyBeldone

**Comment by JimmyBeldone** [comment]
Sorry for the late answer i've been busy.
I just tested it on mac and 2 windows devices, works great ! Thx

**Comment by Etto91** [comment]
merged and publish 1.0.7 ty for your help
