### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by Andyliwr** [Etto91/react-scroll-wheel-handler#21]
![image](https://user-images.githubusercontent.com/12456160/112793296-9ccbde80-9097-11eb-8776-b15921b4cb5e.png)

**Comment by Etto91** [comment]
https://github.com/Etto91/react-scroll-wheel-handler/blob/a770f395825870d9aa5a22e10cd044579cb951db/src/ReactScrollWheelHandler.js#L242
