### ISSUE TITLE
Custom Component

### ISSUE THREAD

**Issue by MochRafi007** [Etto91/react-scroll-wheel-handler#23]
Hello! is there a full example to how use a Custom Component ?
Thanks~

**Comment by Etto91** [comment]
Hi, look at this test

https://github.com/Etto91/react-scroll-wheel-handler/blob/a770f395825870d9aa5a22e10cd044579cb951db/tests/ReactScrollWheelHandler.test.js#L262

**Comment by MochRafi007** [comment]
Thank you very much! @Etto91
