### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by rever96** [Etto91/react-scroll-wheel-handler#27]
I've just tried this package, it works fine! good job.

I had to add to my file `global.d.ts` the string `declare module 'react-scroll-wheel-handler';`
would be fine if you add the @type module

**Comment by Etto91** [comment]
i don't know what you say but make a pr :)

**Comment by rever96** [comment]
Buonasera Ettore,

Mi spiego meglio,

Il tuo package non ha il supporto typescript.

Non so cosa devi fare per aggiungerlo, però se provi ad utilizzarlo in un
progetto react con typescript da errore in compilazione, per risolverlo si
può aggiungere la dichiarazione nel file .d.ts oppure fare npm i @type
nome-del-package che però non esiste per react-scroll-wheel-handler.


Cordiali saluti, Loris Toia

Il Mar 6 Lug 2021, 17:16 Ettore Panini ***@***.***> ha
scritto:

**Comment by Etto91** [comment]
Ciao, non sono esperto di typescript, probabilmente va fatta una build specifica?

**Comment by Etto91** [comment]
@rever96 ho pubblicato la 2.1.0 con index.d.ts file nella cartella dist.
