### ISSUE TITLE
Nesting handlers stops stopPropagation by default.

### ISSUE THREAD

**Issue by nullbytesoftware** [Etto91/react-scroll-wheel-handler#30]
Hi,

I have noticed that the events from nested handlers are not reaching handlers above them. This should not be the default behaviour and the user should stop it intentionally via `e.stopPropagation`.

I have a use case where i want a nested handler to only handle scrolling down and scrolling up should be handled by the root handler. Is it possible to achieve this ?

**Comment by Etto91** [comment]
hi,
could you give me a more specific example?

if you want to open a pr you are welcome :)
