### ISSUE TITLE
"Object doesn't support property or method 'sign'" IE11 Error

### ISSUE THREAD

**Issue by michelecocuccio** [Etto91/react-scroll-wheel-handler#6]
"Math.Sign()" used on line 198 and 211  is not supported by IE11.
Do you offer support for IE11? I am going to use react-scroll-wheel-handler on my plugin, but I am trying to making sure that is IE11 compatible.

Do you think you can make this IE11 Compatible? You could use a Polyfill or take a look here (https://stackoverflow.com/questions/7624920/number-sign-in-javascript)

**Comment by Etto91** [comment]
I have created the pull request. Can you test it on IE11? 
#7

**Comment by michelecocuccio** [comment]
> I have created the pull request. Can you test it on IE11?
> #7

Hey Danilo.
I have just tested it with your new branch (remove-sign) but it still fails... but it shouldn't? I checked my node_modules and I am definitely using the right branch as I can see the changes in the main file. I don't understand why it's not working still. Is the **handleSwipeEnd()** that is failing by the way...
Can I ask why are you also handling Touch Events? Everything works fine in IE11 if I only use the your functionality to scroll (the **upHandler()** and **downHandler()**). The problem is that I am using my own touch event to swipe on an element and when I do it, this error shows up.

<img width="724" alt="Screenshot 2019-06-28 at 20 58 53" src="https://user-images.githubusercontent.com/8071249/60368037-b4b88f00-99e7-11e9-8cb9-2963feb3c06a.png">

Btw I am testing on IE11 using BrowserStack! Maybe you could test it there as well?

Grazie :)

**Comment by Etto91** [comment]
did you have run npm run build?
how is danilo? :)

**Comment by michelecocuccio** [comment]
> did you have run npm run build?
> who is danilo? :)

Ops scusa! :)
Yes I have run NPM run build. I will try to move my touch events somewhere else to avoid conflict with this for now. It's all working fine is just I wanted to offer support for IE11 if possible (I know, it's painful).
Thanks anyway 👍

**Comment by Etto91** [comment]
i have tested it on IE11 on w10 and it works

**Comment by Etto91** [comment]
fix in 1.0.9
