### ISSUE TITLE
Is it possible to add momentum scrolling?

### ISSUE THREAD

**Issue by martinbroos** [Etto91/react-scroll-wheel-handler#8]
Hi, 

First of all thanks for this library, so far it's been a lifesaver. What i trying to solve is if I can add momentum scrolling using the mouse wheel or trackpad. So when the user uses are larger scroll move it will go faster and slowly loses speed afterwards. The same as regular osx trackpad scrolling works.

When using the default wheel event, it will trigger way too much events which will crash the browser. React scroll wheel fixes this, but we lose the ability to use some normalized momentum scrolling. Is this something you think is possible ? And is in the scope of this library?

I'm also looking at https://idiotwu.github.io/smooth-scrollbar/ , the problem there is that it will add transforms to scroll the container, but I'm only looking to handle the events and trigger my own up/down functions.

**Comment by Etto91** [comment]
hi, 
sorry man, but i'm so busy in this period. I'm thinking how to do what you want but i have no idea where to start.
If you want to make a PR i will do my best to add this feature.
